### ISSUE TITLE
Seeing random serialization failures in unit tests

### ISSUE THREAD

**Issue by jeking3** [boostorg/serialization#136]
I can re-run a build job that fails and it disappears.  It's happening around 5% of the time on the jobs I've seen.  This is new behavior as of the last 24 hours or so.

Example:
https://travis-ci.org/boostorg/ptr_container/jobs/448820164#L1935

I'm going to refresh my CI enhancement pull request for this repo to get more coverage.

**Comment by robertramey** [comment]
I have been tweaking a couple of tests.  Hopefully this should get resolved in the course of today.  I can't explain why results fluctuate.  We'll take a look when I make the next set of changes.  Hopefully these will be the last for a while

**Comment by jeking3** [comment]
Manifesting in other ways:
```
testing.capture-output ../../bin.v2/libs/ptr_container/test/serialization.test/clang-linux-6.0/debug/cxxstd-11-iso/visibility-hidden/serialization.run
====== BEGIN OUTPUT ======
==9929== Memcheck, a memory error detector
==9929== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==9929== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==9929== Command: ../../bin.v2/libs/ptr_container/test/serialization.test/clang-linux-6.0/debug/cxxstd-11-iso/visibility-hidden/serialization
==9929== 
Running 1 test case...
test/serialization.cpp(254): error: in "Pointer Container Test Suite/test_serialization": check p->i == d->i has failed [42 != 2]
test/serialization.cpp(256): error: in "Pointer Container Test Suite/test_serialization": check dynamic_cast<Derived*>( d ) has failed
*** 2 failures are detected in the test module "Master Test Suite"
```

**Comment by robertramey** [comment]
or to ptr_container for that matter

**Comment by robertramey** [comment]
I don't think the master branch has changed other than the setting of visibility=hidden as the default.  And THAT could definitely effect the results for any serialization test with the word "ptr" in it.

**Comment by jeking3** [comment]
Let's see what the result is of the expanded CI suite I have running right now.
