### ISSUE TITLE
feature request: add boost::circular_buffer serialization

### ISSUE THREAD

**Issue by yuvalif** [boostorg/serialization#138]
For possible implementation and benchmarking please see [here](https://gist.github.com/yuvalif/aa3691c62959b1a9d7dbf7adceac0c78).

**Comment by correaa** [comment]
Related, https://github.com/boostorg/serialization/issues/132 .

**Comment by yuvalif** [comment]
@correaa thanks, I guess I'll make the change in the circular_buffer repo.

**Comment by yuvalif** [comment]
opened here: https://github.com/boostorg/circular_buffer/issues/24
