### ISSUE TITLE
Boost depreciation of BOOST_*_ENDIAN

### ISSUE THREAD

**Issue by anadon** [boostorg/serialization#155]
I'm trying other ways to run graph tests, and the following came up.

```
clang-linux.compile.c++.without-pch ../../../bin.v2/libs/serialization/build/clang-linux-8.0.0/debug/threading-multi/visibility-hidden/binary_iarchive.o
In file included from ../../../libs/serialization/src/binary_iarchive.cpp:20:
In file included from ../../../boost/archive/impl/basic_binary_iarchive.ipp:25:
In file included from ../../../boost/detail/endian.hpp:9:
../../../boost/predef/detail/endian_compat.h:11:9: warning: The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead [-W#pragma-messages]
#pragma message("The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead")
```

**Comment by robertramey** [comment]
hmmm - seems to me a better place to address this would be in boost/detail/endian.hpp or boost/predef/detail/endian_compat.h .

So I'm closing this issue.  Feel free to re-open it if I'm wrong.

**Comment by Xanderus** [comment]
The warning means that including boost/detail/endian.hpp is deprecated.
archive/impl/basic_binary_iarchive.ipp uses macros BOOST_LITTLE_ENDIAN and BOOST_BIG_ENDIAN; these two should be replaced with BOOST_ENDIAN_*_BYTE, as the message says.

**Comment by pdimov** [comment]
Looks like this has been fixed by https://github.com/boostorg/serialization/pull/125.
