### ISSUE TITLE
XML comments cause exception in boost::archive::xml_iarchive

### ISSUE THREAD

**Issue by HDembinski** [boostorg/serialization#169]
I added a valid XML comment into a valid XML file written by boost::archive::xml_oarchive and this causes `boost::archive::archive_exception: input stream error` when I read the XML back with boost::archive::xml_iarchive. Naturally, it works without the comment. Could it be that xml_iarchive is not skipping comments and this is a bug?

Now you may ask why I have to put a comment into such an XML file. I need this to place a copyright notice into the XML files that I use to test the serialization code in Boost.Histogram.

**Comment by robertramey** [comment]
the xml parser - generated with Boost Spirit is only guaranteed to function with xml generated by the serialization library itself.  So it's basically a subset of xml.

I'm not adverse to enhancing the parser - working with spirit is interesting - but I'm loath to encourage persons to edit the xml archives generated by the serialization library.  I don't know what a "comment" in an xml file is.  Unless it's one more data name/value pair.  If this is the case a really simple way to do this would be to create a data item in your serialization file which contains the copyright notice.  In this case, the copyright notice would always be there.  You'd serialize the copyright notice at the beginning of the archive.

Having just tossed this off the top of my head, I'm thinking it would a a great solution.

**Comment by HDembinski** [comment]
Thank you for the insight. I can understand that you don't want to write a full XML parser. A comment in xml looks like a comment in html, `<!-- this is a comment -->`.
I think the solution you suggest wouldn't work well, as it has to be clear for outsiders that the copyright is not part of the serialized data, but applies to the XML file produced by the serialization.

**Comment by correaa** [comment]
@HDembinski , I think you can distinguish between a "copyrighted save" and the Archive itself. For example when you open the file you can put/get the information there before serializer kicks in. In some sense you are adding a layer to what one calls Save/Load.

(code not tested)
```
void CopyrightedSave(histogram const& h, std::string file = "copyrighted_file.xml"){
std::ofstream ofs{file};
ofs << "<!-- Copyright Dembinski>\n";
xml::serialization::xml_oarchive xoa(ofs);
xoa << BOOST_SERIALIZATION_NVP("root", h);
}
```
```
void CopyrightedLoad(histogram& h, std::string file){
std::ifstream ifs{file};
ifs.getline(); //eat line // or look ahead if is optional
xml::serialization::xml_iarchive xia(ifs);
xia >> BOOST_SERIALIZATION_NVP("root", h);
}
```

This is less invasive that Robert's suggestion because you don't need to add copyright to your data types, why would a histogram know about legal matters? :)

**Comment by HDembinski** [comment]
This is what I am using as workaround already. But I think that an XML parser should handle XML comments.
