### ISSUE TITLE
Boost::serialization declared outside class and giving access to private members

### ISSUE THREAD

**Issue by rachelglenn** [boostorg/serialization#174]
Here is what I am trying to do:

struct Data{
 double variable1;
 double variable2;
};

Class A {
private:
  friend boost::serialization::access;
   boost::shared_ptr<data> pData;
public:
   double getVariable1(){
   return pData->variable1;
}
};

template<class Archive>
void boost::serialization::serialize(Archive & ar, A& aIn, const unsigned int version)
{
ar & aIn.pData->varialble1;
}

I get the the error that I am trying to access a private data member

I have also tried 

template<class Archive>
void boost::serialization::serialize(Archive & ar, A& aIn, const unsigned int version)
{
ar & aIn.getDouble1();
}

I get the error that serialize is ambiguous. Any ideas? Thank you in advance.

**Comment by robertramey** [comment]
try 
template
void boost::serialization::serialize(Archive & ar, A& aIn, const unsigned int version)
{
ar & aln.pData;
}

**Comment by correaa** [comment]
> try
> template
> void boost::serialization::serialize(Archive & ar, A& aIn, const unsigned int version)
> {
> ar & aln.pData;
> }

Is this complete code or Github ate the formatting?

**Comment by robertramey** [comment]
it's the complete code.  you might have to include boost/serialization/shared_ptr.hpp .  Boost serialization has intrinsic support for smart pointers.

**Comment by correaa** [comment]
ok, I didn't understand the syntax, I think that there are some angle brackets missing.

**Comment by robertramey** [comment]
I don't think so.

**Comment by robertramey** [comment]
may I presume that this is fixed.  I want to close it.

**Comment by robertramey** [comment]
Feel free to re-open it if you dig up more information.
