### ISSUE TITLE
Serialization unordered_map.hpp does not support map with custom allocator

### ISSUE THREAD

**Issue by markroizman** [boostorg/serialization#187]
Hello,

It looks like unordered_map.hpp was copied from unordered_set.hpp and type T parameter is missing. The fix is simple - just add and pass T.
template<
    class Archive, 
    class Key, 
    **class T,**
    class HashFcn, 
    class EqualKey,
    class Allocator
>

I attached a test case from the serialization tutorial - just replaced list by unordered_map with custom tbb::scalable_allocator. 
[Bug.gz](https://github.com/boostorg/serialization/files/4041235/Bug.gz)

The same is for unordered_multimap.hpp

Thank you,
Mark

**Comment by robertramey** [comment]
How about tweaking the code, running the tests and submitting a PR?

**Comment by robertramey** [comment]
I'm not seeing that this requires any change to the serialization library itself.  Your change is in the example.  It's only an example which works with either type of collection.  In fact, you could have continued to use the std::list with your custom allocator:
`//    std::list<bus_stop *> stops;
    std::list<
        bus_stop*,
        tbb::scalable_allocator<bus_stop* >
    > stops;
`

**Comment by markroizman** [comment]
Hi Robert,

Unfortunately, I don’t have boost setup to test the change. I don’t have even clean boost sources.
Everything is supplied by our IT.
I’ll be relatively big overhead for me to ramp up to the boost environment, install it and run tests for such a small change.
Please consider asking somebody who can help.

Thanks,
Mark

**Comment by robertramey** [comment]
My point above is that no changes are required in the library.  As you note it already supports custom allocators.  The example you site - is an example - not part of the library itself.  So you're all done!

**Comment by markroizman** [comment]
Hi Robert,

Sorry for being unclear.
There is missing template parameter in serialization/unordered_map.hpp. There must be 5, but in the boost, only 4 are defined and passed through.
If you try my test case, you get compilation error.
The fix is simple, you need to add and pass missing T.

Thanks,
Mark

From C++ reference
template<
    class Key,
    class T,
    class Hash = std::hash<Key>,
    class KeyEqual = std::equal_to<Key>,
    class Allocator = std::allocator< std::pair<const Key, T> >
> class unordered_map;

In Boost
template<
    class Archive,
    class Key,
    class HashFcn,
    class EqualKey,
    class Allocator
>

**Comment by robertramey** [comment]
fixed / tested on my machine.  Will soon upload to develop branch.  So closing this for now.  Thanks for spotting this.

**Comment by markroizman** [comment]
Thank you very much
Mark

**Comment by markroizman** [comment]
Hi Robert,

I’ve just found out that the same problem exists in boost/serialization/boost_unordered_map.hpp
And this file has additional problem – wrong #define, which is the same as in unordered_map.hpp but should have 2x SERIALIZATION_
#define BOOST_SERIALIZATION_ SERIALIZATION_UNORDERED_MAP_HPP

Please check.
Thanks,
Mark

From: Mark Roizman
Sent: Wednesday, January 15, 2020 11:37 PM
To: boostorg/serialization <reply@reply.github.com>
Subject: RE: [boostorg/serialization] Serialization unordered_map.hpp does not support map with custom allocator (#187)

Thank you very much
Mark

**Comment by robertramey** [comment]
OK  - fixed and bumped serialization library version
