### ISSUE TITLE
std::shared_ptr<uint8_t[]> fails to serialize

### ISSUE THREAD

**Issue by knzivid** [boostorg/serialization#190]
```
struct Test {
    std::shared_ptr<uint8_t[]> ptr;

    template <typename Archive>
    void serialize(Archive &ar, size_t) {
        ar & ptr;
    }
};
```

https://www.godbolt.org/z/X3eLnS

This is with boost 1.71

Am I missing something here?

**Comment by robertramey** [comment]
yep you won't be able to  serialization a declaration.  You need to serialize some real data.  So

uint8_t x[10];
std::shared_ptr<uint8_t> px = x; 
..

ar << x will work.
