### ISSUE TITLE
Suspect file in Boost 1.78.0

### ISSUE THREAD

**Issue by Thunder1982** [boostorg/serialization#253]
Hello,

during build of boost 1.78.0 and repackaging the artefact as rpm, we've noticed that a strange file is part of the release:
`$INSTDIR/include/boost/serialization/collection_size_type copy.hpp`
This file leads to errors during rpm build, since the file name contains a whitespace.
The file seems to be the copy of `collection_size_type.hpp`.

Is this file important or could it be deleted?

Thanks

**Comment by robertramey** [comment]
This shouldn't be in there.  I believe it has been removed from the release.  You can remove it. I'll check that it is no longer in there.

**Comment by Thunder1982** [comment]
Thank you for clarification.

**Comment by matthew-dews** [comment]
This file is still present in the 1.82 release.

Comparing `collection_size_type copy.hpp` and `collection_size_type.hpp` it looks like the copy is newer based on the copyright, but it's not 100% clear to me which is the right one to keep. Should the copy still be the one that is deleted, or should its contents be moved to the `collection_size_type.hpp`?

**Comment by vissarion** [comment]
The file `collection_size_type copy.hpp` is still there in 1.83 release. I propose to open this issue and close it once we verify that the file is no longer there.
