### ISSUE TITLE
Performance issue with rehash() in load_unordered_collection()

### ISSUE THREAD

**Issue by BrianWeed** [boostorg/serialization#255]
https://github.com/boostorg/serialization/blob/0ca603daf99888bf059c01ae1bab1b27dbc35ebe/include/boost/serialization/unordered_collections_load_imp.hpp#L62

On Windows, std::unordered_map will never shrink the number of buckets it uses, so when we save a map, the bucket_count is always the MAX that it ever was in that session (no matter how many actual entries are in the map at save-time).  Loading this via load_unordered_collection() will restore that max bucket_count, even when there are only 2 items in the map. 
For example, we have one archive with multiple entries like this:

<count>2</count>
<bucket_count>17961079</bucket_count>

Calling rehash(bucket_count) for this costs 50GB, for a map with only 2 items.

I recommend using count, instead of bucket_count, as in:
s.rehash(count);

That should still pre-allocate an appropriately sized buffer (for performance purposes), while also avoiding the problem when the saved bucket_count no longer makes sense given the actual count.

**Comment by BrianWeed** [comment]
I created a PR, but don't see how to link it to this issue.  (Today is my first time using git and GitHub.)

**Comment by robertramey** [comment]
I don't think there is an explicit way to link between the two.  Just submit the PR and in the comment say that it fixes issue number x.

**Comment by robertramey** [comment]
merged PR
