### ISSUE TITLE
boost deserialization access violation in boost_serialization-vc142-mt-gd-x64-1_80.dll

### ISSUE THREAD

**Issue by danyhm** [boostorg/serialization#272]
Hello,
I'm serializing an object on a x86 app and deserializing it in another x64 app both in windows.
I'm using VS2019 16.11.21 and using boost v1.80 with vcpkg. If i use the default settings of vcpkg to use DLL the following exception is thrown while deserializing the object.

`Exception thrown at 0x00007FFD2A9590D8 (boost_serialization-vc142-mt-gd-x64-1_80.dll) in hvppctrl.exe: 0xC0000005: Access violation executing location 0x00007FFD2A9590D8.` in the file `xlocnum` on line 300

however if i use static libraries with vcpkg the deserialization is done correctly with no errors.

**Comment by robertramey** [comment]
If you can make a small test, I'll look at it.
