### ISSUE TITLE
When will   commented code in iserializer be released ?

### ISSUE THREAD

**Issue by XDU-fish** [boostorg/serialization#279]
The iserializer should throw exception when file_version > version().

I noticed that the commented code had been opend in the develop branch before the 1.81 release. 

 Why it is still being commented in boost 1.81 release?  

Could these code be uncommented in boost 1.82 version?

This is a very important thing that let us know if there is a future version object by throwing an exception.
Thanks!

**Comment by ArielSilver** [comment]
@robertramey 
Should I open a pull request and fix it?

**Comment by robertramey** [comment]
Done
