### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by ArielSilver** [boostorg/serialization#286]
struct base {
    virtual std::string get_name () {
        return STRUCT_STR(base);
    }
    template<class Archive>
    void serialize(Archive &ar, const int version) {
    }
};

struct A : public base {
    virtual std::string get_name () {
        return STRUCT_STR(A);
    }
    template<class Archive>
    void serialize(Archive &ar, const int version) {
        ar & boost::serialization::base_object<base>(*this);
    }
};

struct B : public A {
    B(int _e) {e = _e;}
    B() {}
    virtual std::string get_name () {
        std::cout << e;
        return STRUCT_STR(B);
    }

    template<class Archive>
    void serialize(Archive &ar, const int version) {
        ar & boost::serialization::base_object<A>(*this);
        ar & e;
        ar & p;
    }

    int e;
    ProcessStatus p = UNINITIALIZED;
};

void register_oa_class_type(boost::archive::text_oarchive& oa) {
    oa.register_type<base>();
    oa.register_type<A>();
    oa.register_type<B>();
}

void register_ia_class_type(boost::archive::text_iarchive& ia) {
    ia.register_type<base>();
    ia.register_type<A>();
    ia.register_type<B>();
}

**Comment by robertramey** [comment]
what is this?  May I close this issue?
