### ISSUE TITLE
Consider allowing serialization of classes with user-defined operator& 

### ISSUE THREAD

**Issue by alfC** [boostorg/serialization#72]
BS uses `operator&` as a way to obtain addresses (probably to track identical objects), and therefore the intent is clearly to take the address and not some fancy handler resulting from and hypothetical return type of the user defined `operator&`.

If the user has a custom `operator&` that returns something different than a pointer, serialization fails to compile. If it returns a fake pointer value the program may crash.

The only change necessary, is to replace `&t` by `boost::addressof(t)`.
`boost::addressof` is warrantied  to return the real address of the object in a `decltype(t)*`.

Yes, this is repeat of
https://github.com/boostorg/serialization/pull/41/

I made a pull request (explained in the issue) but it was at a time when I didn't know how use git/github
https://github.com/boostorg/serialization/pull/41/commits and I am afraid the changes didn't go anywhere.

In part I had a hard time making the changes and testing because BS is not a header-only library :)
https://github.com/boostorg/serialization/issues/71

**Comment by robertramey** [comment]
done on develop branch

**Comment by correaa** [comment]
Awesome! thank you for the library.

**Comment by alfC** [comment]
There are couple of additional places that need to be changed as well for this to work:

nvp.hpp:
````
    explicit nvp(const char * name_, T & t) :
        // note: added _ to suppress useless gcc warning
        std::pair<const char *, T *>(name_, --& t--++boost::adressof(t)++)
    {}
```
iserializer.hpp
```
             void * x = --&--++boost::addressof(++ const_cast<T &>(t) ++)++;
```

**Comment by robertramey** [comment]
What the heck is this?  It doesn't even look like C++.  It's impossible for me to verify.  Did you actually run the test suite on this?  If this can't be resolved, I'll have to back out the original change.

**Comment by alfC** [comment]
On Thu, Nov 9, 2017 at 10:20 AM, Robert Ramey <notifications@github.com>
wrote:

> What the heck is this? It doesn't even look like C++.
>
Sorry for the confusion. What I mean is that
in nvp.hpp:

std::pair<const char *, T *>(name_, & t)

...needs to be replaced by:

std::pair<const char *, T *>(name_, boost::adressof(t))

and in iserializer.hpp

             void * x = & const_cast<T &>(t);

...needs to be replaced by

             void * x = boost::addressof(const_cast<T &>(t));

It's impossible for me to verify. Did you actually run the test suite on
> this?
>
Yes, these are the changes I made and they worked.

> If this can't be resolved, I'll have to back out the original change.
>
I hope the misunderstanding is resolved. I regret being too creative with
the notation (-- remove-- and ++add++). At the end it is no different to
what is was done to oserializar.hpp, and the changes are independent,
completing this changes will make the class with operator& word for both,
serialization, deserialization and as part NVP xml.

**Comment by alfC** [comment]
Also perhaps to minimize code, it may be useful to use only boost::addressof, which does the job, and if boost::addressof is later implemented in terms of std::addressof at the end is going to be the same. Just a suggestion.
