### ISSUE TITLE
The 8bbcca5341fa3eabb6d0ab83c5f655ccceabf41f breaks library for mingw(-64)/gcc

### ISSUE THREAD

**Issue by eldiener** [boostorg/serialization#78]
SHA 8bbcca5341fa3eabb6d0ab83c5f655ccceabf41f breaks the build of the serialization library for mingw(-64)/gcc. None of the updates after that fix the library for mingw(-64)/gcc. In the update prior to 8bbcca5341fa3eabb6d0ab83c5f655ccceabf41f the library builds without error for mingw(-64)/gcc.

**Comment by eldiener** [comment]
A quick note that the update above that breaks the build of the serialization library for mingw(-64)/gcc says in the git log:

"* fixed addressor fiasco
simplified singleton visibility
Jamfile
added boost/system to requirements
corrected inclusion tests to include link to serialization library"

**Comment by eldiener** [comment]
I am glad to see this has now been fixed. Thanks !

**Comment by robertramey** [comment]
Appreciate the fact that you're pointing this stuff out.  I strive for perfection - but it's not easy in this world!  Thanks for you help.
